FROM ubuntu:20.04

# Variables d'environnement
ENV MYSQL_DATABASE: 'dbcloud'
      # So you don't have to use root, but you can if you like
ENV MYSQL_USER: 'user'
      # You can use whatever password you like
ENV MYSQL_PASSWORD: 'password'
      # Password for root access
ENV MYSQL_ROOT_PASSWORD: 'password'

ENV DEBIAN_FRONTEND=noninteractive
ENV ENVIRONMENT=DEV-DOCKER

# Installation mysql,  et extensions
RUN apt-get update
RUN apt-get install -y mysql-server
RUN apt-get install -y wget
RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb
RUN apt-get install -y lsb-release
RUN apt-get install -y gnupg
RUN dpkg -i mysql-apt-config_0.8.24-1_all.deb
RUN apt-get update
RUN apt-get install -y mysql-shell