version: '3.3'
services:
  db_local:
    tty: true
    image: mysql:5.7
    container_name: dblocal
    networks:
      - iotnetwork
    build: 
      context: .
      dockerfile: dockerfile-db
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "db_local"]
        interval: 1s
        timeout: 1s
        retries: 10
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'AirLuxDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - local-db:/var/lib/mysql
      
  db_cloud:
    tty: true
    image: mysql:5.7
    container_name: dbcloud
    networks:
      - iotnetwork
    build: 
      context: .
      dockerfile: dockerfile-db
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "db_cloud"]
        interval: 1s
        timeout: 1s
        retries: 10
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'AirLuxDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - cloud-db:/var/lib/mysql
      
  syncapi:
    tty: true
    image: bitnami/laravel
    container_name: syncapi
    networks:
      - iotnetwork
    depends_on:
      db_cloud:
        condition: service_healthy
      db_local:
        condition: service_healthy
    healthcheck:
        test: "curl -f http://syncapi/api/captor/:80"
        interval: 2s
        timeout: 2s
        retries: 10
    build: 
      context: ./..
      dockerfile: docker/dockerfile-laravel
    working_dir: /var/www/
    ports:
      - "80:80"
    extra_hosts:
        host.docker.internal: host-gateway
    environment:
      LOCAL_DATABASE: 'dblocal'
      DISTANT_DATABASE: 'dbcloud'
      MYSQL_DATABASE: 'AirLuxDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # Where our data will be persisted
    volumes:
      - syncapp:/var/www
      
  pulsor:
    tty: true
    image: ubuntu
    container_name: pulsor
    networks:
      - iotnetwork
    depends_on:
      syncapi:
        condition: service_healthy
    build: 
      context: .
      dockerfile: dockerfile-pulsor
    environment:
      LOCAL_DATABASE: 'db_local'
      DISTANT_DATABASE: 'db_cloud'
      API: 'syncapi'
    volumes:
      - pulsor:/var/www
            
# Names our volume
volumes:
  local-db: 
  cloud-db: 
  syncapp: 
  pulsor: 
  
networks:
  iotnetwork: