
FROM php:7.4-fpm as build

# Arguments defined in docker-compose.yml (not really bruh)
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u 1000 -d /home/user user
RUN mkdir -p /home/user/.composer && \
    chown -R user:user /home/user

COPY sync-api/README.md /var/www/sync-api/README.md
#COPY docker/set_up_api.sh /root/set_up_api.sh


# Run necessary services
#RUN chmod u+x set_up_api.sh
#ENTRYPOINT ["/bin/bash", "/root/set_up_api.sh"]

#COPY /sync-api/ /var/www/sync-api/

# Set working directory
#WORKDIR /root
#RUN git clone https://github.com/bjausseran/BddSyncTest.git \
#    && mv /root/BddSyncTest/sync-api /var/www/sync-api

    
#WORKDIR /var/www/sync-api

#FROM ubuntu:18.04 as build2
#COPY --from=build /root/BddSyncTest/sync-api/ /var/www/sync-api/

#USER user
