FROM ubuntu:18.04


# Variables d'environnement

# Installation mysql,  et extensions
RUN apt-get update \
&& apt-get install -y mysql-server \
&& apt-get install -y wget \
&& wget https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb \
&& apt-get install -y lsb-release \
&& apt-get install -y gnupg \
&& dpkg -i mysql-apt-config_0.8.24-1_all.deb \
&& apt-get update \
&& apt-get install -y mysql-shell

COPY set_up_base.sh /root/set_up_base.sh
# CMD chmod +x /root/set_up_base.sh && exec /root/set_up_base.sh