FROM ubuntu:18.04

# Install system dependencies
RUN apt-get update && apt-get -qq -y install curl && apt-get install -y telnet

WORKDIR /home/
COPY /pulsor.sh /home/pulsor.sh

# Run necessary services
RUN chmod u+x pulsor.sh
ENTRYPOINT ["/bin/bash", "/home/pulsor.sh"]