version: '3.3'
services:
  syncapp:
    image: bitnami/laravel
    restart: no
    working_dir: /var/www/
    environment:
      LOCAL_DATABASE: 'db local'
      LOCAL_PORT: 3306
      DISTANT_DATABASE: 'db cloud'
      DISTANT_PORT: 3307
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3305:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      - '3307'
      - '3305'
      # Where our data will be persisted
    volumes:
      - my-syncapp:/var/www
# Names our volume
volumes:
  my-syncapp: